### PR TITLE
Fix issues with check_tree test

### PR DESCRIPTION
**Pull request by msteinert**
This patch fixes a few issues in the check_tree test:

* Fix various memory leaks in test code
* Fix a double-free in test code
* Fix a memory leak in r3_tree_compile_patterns

One memory leak remains in the library code but it isn't obvious to me
how to fix it at the moment.

### CODE REVIEW

**Comment by msteinert** [comment]
After launching a Trusy Docker container to replicate the Travis build environment:

```
90%: Checks: 21, Failures: 0, Errors: 2
check_tree.c:108:E:common_prefix_testcase:test_find_common_prefix_after:0: (after this point) Test timeout expired
check_tree.c:158:E:common_prefix_testcase:test_find_common_prefix_middle:0: (after this point) Test timeout expired
```

I don't see these errors with newer versions of libcheck. I'll try to dig a bit more and figure out what's going on.

**Comment by c9s** [comment]
Thanks

**Comment by msteinert** [comment]
I verified that the problem seems to be this particular version of libcheck:

```
root@ea214385b258:/build/r3/tests# apt-cache policy check
check:
  Installed: (none)
  Candidate: 0.9.10-6ubuntu3
  Version table:
     0.9.10-6ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
root@ea214385b258:/build/r3/tests# gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I updated to the latest version (from source) and everything runs fine. I see a couple ways to solve the problem:

1. Install libcheck from source in the CI script (instead of from the repo)
2. Update the CI environment to a newer version of Ubuntu

16.04 has version check 0.10, which appears to work fine.

Thoughts?

**Comment by msteinert** [comment]
I went ahead and update the CI configuration to build inside a 16.04 Docker container. Let me know what you think.

**Comment by msteinert** [comment]
I believe this is ready merge if you're happy with the changes.

**Comment by c9s** [comment]
They look awesome! Thanks

**Pull request merged**
