### PR TITLE
Add Coverity Scan to CI

### LINKED ISSUE #110: Set up coverity scan in CI
Right now I'm scanning the code manually but we can use the coverity scan plugin to submit the builds periodically.
coverity scan can find errors other linters can't.

### PR DESCRIPTION
**Pull request by bjosv**
Coverity is a static code analysis tool which can find and warn about many hard-to-find faults.
This PR adds a CI job that triggers a scan, and a correction of the last existing issue.

Results will be available at:
https://scan.coverity.com/projects/r3

Fixes #110

### CODE REVIEW

**Comment by bjosv** [comment]
@c9s If you also think this would be a good tool to run in CI then I will update the PR before it can be merged.
Updates are needed to use `secrets.COVERITY_TOKEN` and to update the email to yours before merging this. Then I will add you as admin in the Coverity project, so that you can regenerate a token on the Coverity project webpage by the click of a button and add that as a Github secret.

**Comment by c9s** [comment]
@bjosv sure! let's do this

**Comment by c9s** [comment]
@bjosv I can add you as a collaborator of this repo ;)

**Comment by bjosv** [comment]
> @bjosv I can add you as a collaborator of this repo ;)

It's a badge of honor, thanks :)
I now added you as owner of the project in https://scan.coverity.com/projects/r3 
The coverity job failed after the last change due to the missing Github secret COVERITY_TOKEN that needs to be configured in the Github project (Settings/Secret which I cant access) and it needs to be set to the `Project token` got from: https://scan.coverity.com/projects/r3?tab=project_settings

**Review by c9s — APPROVED** [review]

**Comment by c9s** [comment]
Sorry for the slow update! I just added the token 

image

**Pull request merged**
