### PR TITLE
Slug parse, changed memory model, few optimizations

### PR DESCRIPTION
**Pull request by karantin2020**
See comment to commit

### CODE REVIEW

**Comment by karantin2020** [comment]
If it will not merge well on that branch then you can test changes on my fork with branch krn_feature

**Comment by c9s** [comment]
Merged to 2.0 branch. Thanks!

**Comment by c9s** [comment]
@karantin2020  I'm wondering about where the memory.h from. I saw there is a copyright "Copyright (c) 2014 DeNA Co., Ltd.", there might be a licensing issue. what's the license type?

**Comment by karantin2020** [comment]
see https://github.com/h2o/h2o
MIT license

Names of function were changes because of conflicts with that lib

I just use my branch of r3 and h2o for my use cases
Soon I will publish that repo

**Comment by karantin2020** [comment]
krn_feature branch merged. Close PR

**Comment by c9s** [comment]
Hi @karantin2020 there is a build error after merging your changes, could you take a look please? otherwise I might have to revert the merge to make keep the build status stable.

**Comment by karantin2020** [comment]
Error in commit "Clean heap after use in simple example"?

**Comment by karantin2020** [comment]
I tested now current branch 2.0. Everything compiles well, all tests done.
What kind of error do you have?

In commits comment I wrote that few API was changed

**Comment by c9s** [comment]
Sorry I forgot to paste the travis ci url, one moment

**Comment by c9s** [comment]
https://travis-ci.org/c9s/r3

**Comment by karantin2020** [comment]
Travis log above shows only error in "Clean heap after use in simple example".
Current travis error is in  "Fix fprintf warning" commit.

All tests and examples execute well.

What is the error reason? May be travis config?

Travis log shows error in "r3 core tests" suite (endless execution). On my local machine everything works fine.
Did you find anything else?

**Pull request closed without merging**
